language: c
addons:
    apt:
        packages:
        - build-essential

script:
  - >
      DIRS=(Part1/HW01Linux Part1/HW01Linux  Part1/HW02Sort Part1/HW03Cake Part1/HW04File Part1/HW05Sum Part1/HW06Word Part2/HW07QSort Part3/HW16BinaryTree2);
      TEST=(yes             no               no             no             no             no            no             no              no);
      for((i=0;i<${#DIRS[@]};i++));
        do
           if [[ "${TEST[$i]}" == "yes" ]]; then
              echo "Running Test $i in directory ${DIRS[$i]} (yes)";
              make -C "${DIRS[$i]}" && make -C "${DIRS[$i]}" testall;
           else
              echo "Not Running Test $i in directory ${DIRS[$i]} (not yes)";
           fi;
        done;
