language: c
addons:
    apt:
        packages:
        - build-essential

# Note: The formatting below is NOT required. It is intentional so you can configure which tests to run, visually.
# THe arrays DIRS and TEST are in 1-1 correspondence
env:
    - DIRS=(Part1/HW01Linux Part1/HW02Sort Part1/HW03Cake Part1/HW04File Part1/HW05Sum Part1/HW06Word Part2/HW07QSort Part3/HW16BinaryTree2) TEST=(yes no no no no no no no)

script:
  - for((i=0;i<${#DIRS[@]};i++)); do if [[ "${TEST[$i]}" == "yes" ]]; then make -C "${DIRS[$i]}" && make -C "${DIRS[$i]}" testall; fi; done
  - true

